export const ICONOS_BASE = {
  anti: "mapa_antiguedades.jpg",
  art: "mapa_arte_pintura.jpg",
  beauty: "mapa_belleza.jpg",
  bicycle: "mapa_bici.jpg",
  bolsos: "mapa_bolsos.jpg",
  coffee: "mapa_cafe.jpg",
  carniceria: "mapa_carniceria.jpg",
  butcher: "mapa_carniceria.jpg",
  cerrajeria: "mapa_cerrajeria.jpg",
  locksmith: "mapa_cerrajeria.jpg",
  confiteria: "mapa_confiteria.jpg",
  pastry: "mapa_confiteria.jpg",
  concesionario: "mapa_consesionario.jpg",
  car: "mapa_consesionario.jpg",
  furniture: "mapa_hogar.jpg",
  interior_decoration: "mapa_hogar.jpg",
  clothes: "mapa_ropa.jpg",
  supermarket: "mapa_supermecado.jpg",
  bakery: "mapa_panaderia.jpg",
  sports: "mapa_deporte.jpg",
  jewelry: "mapa_joyeria.jpg",
  shoes: "mapa_zapateria.jpg",
  optician: "mapa_optica.jpg",
  hairdresser: "mapa_peluqueria.jpg",
  florist: "mapa_floristeria.jpg",
  greengrocer: "mapa_frutas_verduras.jpg",
  laundry: "mapa_lavanderia.jpg",
  stationery: "mapa_libros_papeleria.jpg",
  books: "mapa_libros_papeleria.jpg",
  lighting: "mapa_iluminacion.jpg",
  electronics: "mapa_electronica.jpg",
  mobile_phone: "mapa_electronica.jpg",
  telecommunication: "mapa_electronica.jpg",
  pharmacy: "mapa_farmacia.jpg",
  toys: "mapa_jugueteria.jpg",
  music: "mapa_musica.jpg",
  photo: "mapa_fotografia.jpg",
  tailor: "mapa_sastreria_costureria.jpg",
  copyshop: "mapa_copisteria.jpg",
  lottery: "mapa_loteria.jpg",
  tattoo: "mapa_tatuajes.jpg",

  hardware: "mapa_hardware.jpg",
  car_parts: "mapa_consesionario.jpg",
  fireplace: "mapa_chimenea.png",
  car_repair: "mapa_consesionario.jpg"
};

export const TRADUCCIONES_TIPO = {
  anti: "Antigüedades",
  art: "Arte",
  beauty: "Belleza",
  bicycle: "Bicicletas",
  bolsos: "Bolsos",
  coffee: "Café",
  carniceria: "Carnicerías",
  butcher: "Carnicerías",
  cerrajeria: "Cerrajerías",
  locksmith: "Cerrajerías",
  confiteria: "Confiterías",
  pastry: "Confiterías",
  concesionario: "Concesionarios",
  car: "Concesionarios",
  furniture: "Hogar",
  interior_decoration: "Decoración",
  clothes: "Ropa",
  supermarket: "Supermercados",
  bakery: "Panaderías",
  sports: "Deporte",
  jewelry: "Joyerías",
  shoes: "Zapaterías",
  optician: "Ópticas",
  hairdresser: "Peluquerías",
  florist: "Floristerías",
  greengrocer: "Fruterías",
  laundry: "Lavanderías",
  stationery: "Papelerías",
  books: "Librerías",
  lighting: "Iluminación",
  electronics: "Electrónica",
  mobile_phone: "Móviles",
  telecommunication: "Telecomunicaciones",
  pharmacy: "Farmacias",
  toys: "Jugueterías",
  music: "Música",
  photo: "Fotografía",
  tailor: "Sastrerías",
  copyshop: "Copisterías",
  lottery: "Lotería",
  tattoo: "Tatuajes",

  hardware: "Herramientas",
  car_parts: "Piezas de coche",
  fireplace: "Chimeneas",
  car_repair: "Reparaciones de coches"
};

export const ETIQUETAS = {
  "mapa_antiguedades.jpg": "Antigüedades",
  "mapa_arte_pintura.jpg": "Arte",
  "mapa_belleza.jpg": "Belleza",
  "mapa_bici.jpg": "Bicis",
  "mapa_bolsos.jpg": "Bolsos",
  "mapa_cafe.jpg": "Café",
  "mapa_carniceria.jpg": "Carnicerías",
  "mapa_cerrajeria.jpg": "Cerrajerías",
  "mapa_confiteria.jpg": "Confiterías",
  "mapa_consesionario.jpg": "Concesonarios",
  "mapa_hogar.jpg": "Hogar",
  "mapa_ropa.jpg": "Ropa",
  "mapa_supermecado.jpg": "Supermercados",
  "mapa_panaderia.jpg": "Panaderías",
  "mapa_deporte.jpg": "Deporte",
  "mapa_joyeria.jpg": "Joyas",
  "mapa_zapateria.jpg": "Calzado",
  "mapa_optica.jpg": "Ópticas",
  "mapa_peluqueria.jpg": "Peluquerías",
  "mapa_floristeria.jpg": "Floristerías",
  "mapa_frutas_verduras.jpg": "Fruterías",
  "mapa_lavanderia.jpg": "Lavanderías",
  "mapa_libros_papeleria.jpg": "Librerías",
  "mapa_iluminacion.jpg": "Iluminación",
  "mapa_electronica.jpg": "Electrónica",
  "mapa_farmacia.jpg": "Farmacias",
  "mapa_jugueteria.jpg": "Juguetes",
  "mapa_musica.jpg": "Música",
  "mapa_fotografia.jpg": "Fotografía",
  "mapa_sastreria_costureria.jpg": "Sastrerías",
  "mapa_copisteria.jpg": "Copisterías",
  "mapa_loteria.jpg": "Loterías",
  "mapa_tatuajes.jpg": "Tatuajes",

  "mapa_chimenea.png": "Chimeneas",
  "mapa_hardware.jpg": "Herramientas"
};