export const ICONOS_BASE = {
  anti: "mapa_antiguedades.jpg",
  art: "mapa_arte_pintura.jpg",
  beauty: "mapa_belleza.jpg",
  bicycle: "mapa_bici.jpg",
  bolsos: "mapa_bolsos.jpg",
  coffee: "mapa_cafe.jpg",
  carniceria: "mapa_carniceria.jpg",
  butcher: "mapa_carniceria.jpg",
  cerrajeria: "mapa_cerrajeria.jpg",
  locksmith: "mapa_cerrajeria.jpg",
  confiteria: "mapa_confiteria.jpg",
  pastry: "mapa_confiteria.jpg",
  concesionario: "mapa_consesionario.jpg",
  car: "mapa_consesionario.jpg",
  furniture: "mapa_hogar.jpg",
  interior_decoration: "mapa_hogar.jpg",
  clothes: "mapa_ropa.jpg",
  supermarket: "mapa_supermecado.jpg",
  bakery: "mapa_panaderia.jpg",
  sports: "mapa_deporte.jpg",
  jewelry: "mapa_joyeria.jpg",
  shoes: "mapa_zapateria.jpg",
  optician: "mapa_optica.jpg",
  hairdresser: "mapa_peluqueria.jpg",
  florist: "mapa_floristeria.jpg",
  greengrocer: "mapa_frutas_verduras.jpg",
  laundry: "mapa_lavanderia.jpg",
  stationery: "mapa_libros_papeleria.jpg",
  books: "mapa_libros_papeleria.jpg",
  lighting: "mapa_iluminacion.jpg",
  electronics: "mapa_electronica.jpg",
  mobile_phone: "mapa_electronica.jpg",
  telecommunication: "mapa_electronica.jpg",
  pharmacy: "mapa_farmacia.jpg",
  toys: "mapa_jugueteria.jpg",
  music: "mapa_musica.jpg",
  photo: "mapa_fotografia.jpg",
  tailor: "mapa_sastreria_costureria.jpg",
  copyshop: "mapa_copisteria.jpg",
  lottery: "mapa_loteria.jpg",
  tattoo: "mapa_tatuajes.jpg",

  hardware: "mapa_bici.jpg",
  car_parts: "mapa_consesionario.jpg",
  fireplace: "mapa_chimenea.png",
  car_repair: "mapa_consesionario.jpg"
};

export const TRADUCCIONES_TIPO = {
  anti: "Antigüedades",
  art: "Arte",
  beauty: "Belleza",
  bicycle: "Bicicletas",
  bolsos: "Bolsos",
  coffee: "Café",
  carniceria: "Carnicería",
  butcher: "Carnicería",
  cerrajeria: "Cerrajería",
  locksmith: "Cerrajería",
  confiteria: "Confitería",
  pastry: "Confitería",
  concesionario: "Concesionario",
  car: "Concesionario",
  furniture: "Hogar",
  interior_decoration: "Decoración",
  clothes: "Ropa",
  supermarket: "Supermercado",
  bakery: "Panadería",
  sports: "Deporte",
  jewelry: "Joyería",
  shoes: "Zapatería",
  optician: "Óptica",
  hairdresser: "Peluquería",
  florist: "Floristería",
  greengrocer: "Frutería",
  laundry: "Lavandería",
  stationery: "Papelería",
  books: "Librería",
  lighting: "Iluminación",
  electronics: "Electrónica",
  mobile_phone: "Móviles",
  telecommunication: "Telecomunicaciones",
  pharmacy: "Farmacia",
  toys: "Juguetería",
  music: "Música",
  photo: "Fotografía",
  tailor: "Sastrería",
  copyshop: "Copistería",
  lottery: "Lotería",
  tattoo: "Tatuajes",

  hardware: "Herramientas",
  car_parts: "Piezas de coche",
  fireplace: "Chimeneas",
  car_repair: "Reparaciones de coches"
};

export const ETIQUETAS = {
  "mapa_antiguedades.jpg": "Antigüedades",
  "mapa_arte_pintura.jpg": "Arte",
  "mapa_belleza.jpg": "Belleza",
  "mapa_bici.jpg": "Bicis",
  "mapa_bolsos.jpg": "Bolsos",
  "mapa_cafe.jpg": "Café",
  "mapa_carniceria.jpg": "Carnicería",
  "mapa_cerrajeria.jpg": "Cerrajería",
  "mapa_confiteria.jpg": "Confitería",
  "mapa_consesionario.jpg": "Concesonario",
  "mapa_hogar.jpg": "Hogar",
  "mapa_ropa.jpg": "Ropa",
  "mapa_supermecado.jpg": "Supermercado",
  "mapa_panaderia.jpg": "Panadería",
  "mapa_deporte.jpg": "Deporte",
  "mapa_joyeria.jpg": "Joyas",
  "mapa_zapateria.jpg": "Calzado",
  "mapa_optica.jpg": "Óptica",
  "mapa_peluqueria.jpg": "Peluquería",
  "mapa_floristeria.jpg": "Floristería",
  "mapa_frutas_verduras.jpg": "Frutería",
  "mapa_lavanderia.jpg": "Lavandería",
  "mapa_libros_papeleria.jpg": "Librería",
  "mapa_iluminacion.jpg": "Iluminación",
  "mapa_electronica.jpg": "Electrónica",
  "mapa_farmacia.jpg": "Farmacia",
  "mapa_jugueteria.jpg": "Juguetes",
  "mapa_musica.jpg": "Música",
  "mapa_fotografia.jpg": "Fotografía",
  "mapa_sastreria_costureria.jpg": "Sastrería",
  "mapa_copisteria.jpg": "Copistería",
  "mapa_loteria.jpg": "Lotería",
  "mapa_tatuajes.jpg": "Tatuajes",

  "mapa_chimenea.png": "Chimeneas"
};